name: mde
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - asttokens=3.0.1
  - blas=1.0
  - bottleneck=1.4.2
  - brotlicffi=1.2.0.0
  - bzip2=1.0.8
  - ca-certificates=2026.1.4
  - certifi=2026.1.4
  - cffi=2.0.0
  - charset-normalizer=3.4.4
  - colorama=0.4.6
  - comm=0.2.3
  - cuda-cccl=13.1.115
  - cuda-cccl_win-64=13.1.115
  - cuda-cudart=11.8.89
  - cuda-cudart-dev=11.8.89
  - cuda-cupti=11.8.87
  - cuda-libraries=11.8.0
  - cuda-libraries-dev=11.8.0
  - cuda-nvrtc=11.8.89
  - cuda-nvrtc-dev=11.8.89
  - cuda-nvtx=11.8.86
  - cuda-profiler-api=13.1.115
  - cuda-runtime=11.8.0
  - cuda-version=13.1
  - debugpy=1.8.20
  - decorator=5.2.1
  - exceptiongroup=1.3.1
  - executing=2.2.1
  - expat=2.7.4
  - filelock=3.20.3
  - freetype=2.14.1
  - giflib=5.2.2
  - gmp=6.3.0
  - gmpy2=2.2.2
  - icc_rt=2022.1.0
  - idna=3.11
  - intel-openmp=2023.1.0
  - ipykernel=7.2.0
  - jedi=0.19.2
  - jinja2=3.1.6
  - jpeg=9f
  - jupyter_client=8.8.0
  - jupyter_core=5.9.1
  - krb5=1.21.3
  - lcms2=2.16
  - lerc=3.0
  - libcublas=11.11.3.6
  - libcublas-dev=11.11.3.6
  - libcufft=10.9.0.58
  - libcufft-dev=10.9.0.58
  - libcurand=10.4.1.81
  - libcurand-dev=10.4.1.81
  - libcusolver=11.4.1.48
  - libcusolver-dev=11.4.1.48
  - libcusparse=11.7.5.86
  - libcusparse-dev=11.7.5.86
  - libdeflate=1.17
  - libexpat=2.7.4
  - libffi=3.4.4
  - libhwloc=2.12.1
  - libiconv=1.16
  - libjpeg-turbo=2.0.0
  - libnpp=11.8.0.86
  - libnpp-dev=11.8.0.86
  - libnvjpeg=11.9.0.86
  - libnvjpeg-dev=11.9.0.86
  - libpng=1.6.54
  - libsodium=1.0.20
  - libtiff=4.5.1
  - libuv=1.48.0
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxml2=2.13.9
  - libzlib=1.3.1
  - lz4-c=1.9.4
  - markupsafe=3.0.2
  - matplotlib-inline=0.2.1
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - nest-asyncio=1.6.0
  - networkx=3.4.2
  - numexpr=2.11.0
  - numpy=2.2.5
  - numpy-base=2.2.5
  - openjpeg=2.5.2
  - openssl=3.6.1
  - packaging=25.0
  - pandas=2.3.3
  - parso=0.8.5
  - pickleshare=0.7.5
  - pillow=11.1.0
  - pip=25.3
  - platformdirs=4.5.1
  - prompt-toolkit=3.0.52
  - psutil=7.2.2
  - pure_eval=0.2.3
  - pycparser=2.23
  - pygments=2.19.2
  - pysocks=1.7.1
  - python=3.10.19
  - python-dateutil=2.9.0post0
  - python-tzdata=2025.3
  - python_abi=3.10
  - pytorch=2.5.1
  - pytorch-cuda=11.8
  - pytorch-mutex=1.0
  - pytz=2025.2
  - pywin32=311
  - pyyaml=6.0.3
  - pyzmq=27.1.0
  - requests=2.32.5
  - scipy=1.15.3
  - setuptools=72.1.0
  - six=1.17.0
  - sqlite=3.51.1
  - stack_data=0.6.3
  - tbb=2021.8.0
  - tbb-devel=2021.8.0
  - tk=8.6.15
  - tornado=6.5.4
  - traitlets=5.14.3
  - typing_extensions=4.15.0
  - tzdata=2025c
  - ucrt=10.0.22621.0
  - urllib3=2.6.3
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vs2015_runtime=14.44.35208
  - wheel=0.46.3
  - win_inet_pton=1.1.0
  - xz=5.6.4
  - yaml=0.2.5
  - zeromq=4.3.5
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - accelerate==1.12.0
      - annotated-types==0.7.0
      - anyio==4.12.1
      - attrs==25.4.0
      - beautifulsoup4==4.14.3
      - black==26.1.0
      - click==8.3.1
      - cryptography==46.0.5
      - fsspec==2026.2.0
      - h11==0.16.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==1.4.1
      - ipython==8.38.0
      - jsonschema==4.26.0
      - jsonschema-specifications==2025.9.1
      - librt==0.7.8
      - lxml==6.0.2
      - markdown==3.10.1
      - markdown-it-py==4.0.0
      - mdurl==0.1.2
      - mypy==1.19.1
      - mypy-extensions==1.1.0
      - pathspec==1.0.4
      - pdfminer-six==20251230
      - pdfplumber==0.11.9
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pypdf==6.7.0
      - pypdfium2==5.4.0
      - pytokens==0.4.1
      - referencing==0.37.0
      - regex==2026.1.15
      - rich==14.3.2
      - rpds-py==0.30.0
      - ruff==0.15.0
      - safetensors==0.7.0
      - sentencepiece==0.2.1
      - shellingham==1.5.4
      - soupsieve==2.8.3
      - sympy==1.13.1
      - tabulate==0.9.0
      - tenacity==9.1.4
      - tokenizers==0.22.2
      - tomli==2.4.0
      - torchaudio==2.5.1
      - torchvision==0.20.1
      - tqdm==4.67.3
      - transformers==5.1.0
      - typer-slim==0.21.1
      - typing-inspection==0.4.2
      - wcwidth==0.6.0
prefix: C:\Users\danie\anaconda3\envs\mde
